module.exports = [
  { country: 'Afghanistan', name: 'Afghanistani Afghani', cc: 'AFN', symbol: '؋' },
  { country: 'Armenia', name: 'Armenian Dram', cc: 'AMD', symbol: 'դր' },
  { country: 'Azerbaijan', name: 'Azerbaijani Manat', cc: 'AZN', symbol: '₼' },
  { country: 'Bahrain', name: 'Bahraini Dinar', cc: 'BHD', symbol: '.د.ب ' },
  { country: 'Bangladesh', name: 'Bangladeshi Taka', cc: 'BDT', symbol: '৳' },
  { country: 'Bhutan', name: 'Bhutanese Ngultrum', cc: 'BTN', symbol: 'Nu.' },
  { country: 'Brunei', name: 'Brunei Dollar', cc: 'BND', symbol: '$' },
  { country: 'Cambodia', name: 'Cambodian Riel', cc: 'KHR', symbol: '៛' },
  { country: 'China', name: 'Chinese Yuan Renminbi', cc: 'CNY', symbol: '¥' },
  { country: 'Cyprus', name: 'Cypriot Pound', cc: 'CYP', symbol: '£' },
  { country: 'Georgia', name: 'Georgian Lari', cc: 'GEL', symbol: ' ლ' },
  { country: 'India', name: 'Indian Rupee', cc: 'INR', symbol: '₹' },
  { country: 'Indonesia', name: 'Indonesian Rupiah', cc: 'IDR', symbol: 'Rp' },
  { country: 'Iran', name: 'Iranian Rial', cc: 'IRR', symbol: '﷼' },
  { country: 'Iraq', name: 'Iraqi Dinar', cc: 'IQD', symbol: 'ع.د' },
  { country: 'Israel', name: 'Israeli New Sheqel', cc: 'ILS', symbol: '₪' },
  { country: 'Japan', name: 'Japanese Yen', cc: 'JPY', symbol: '¥' },
  { country: 'Jordan', name: 'Jordanian Dinar', cc: 'JOD', symbol: 'د.ا' },
  { country: 'Kazakhstan', name: 'Kazakhstani Tenge', cc: 'KZT', symbol: 'лв' },
  { country: 'Kuwait', name: 'Kuwaiti Dinar', cc: 'KWD', symbol: 'د.ك ' },
  { country: 'Kyrgyzstan', name: 'Kyrgyzstani Som', cc: 'KGS', symbol: 'лв' },
  { country: 'Laos', name: 'Lao Kip', cc: 'LAK', symbol: '₭' },
  { country: 'Lebanon', name: 'Lebanese Pound', cc: 'LBP', symbol: '£' },
  { country: 'Malaysia', name: 'Malaysian Ringgit', cc: 'MYR', symbol: 'RM' },
  { country: 'Maldives', name: 'Maldives Rufiyaa', cc: 'MVR', symbol: 'Rf' },
  { country: 'Mongolia', name: 'Mongolian Tugrik', cc: 'MNT', symbol: '₮' },
  { country: 'Myanmar (Burma)', name: 'Myanmar Kyat', cc: 'MMK', symbol: 'K' },
  { country: 'Nepal', name: 'Nepalese Rupee', cc: 'NPR', symbol: '₨' },
  { country: 'North Korea', name: 'North Korean Won', cc: 'KPW', symbol: '₩' },
  { country: 'Oman', name: 'Omani Rial', cc: 'OMR', symbol: '﷼' },
  { country: 'Pakistan', name: 'Pakistan Rupee', cc: 'PKR', symbol: '₨' },
  { country: 'Palestine', name: 'Jordanian Dinar', cc: 'JOD', symbol: 'د.ا' },
  { country: 'Philippines', name: 'Philippine Peso', cc: 'PHP', symbol: '₱' },
  { country: 'Qatar', name: 'Qatari Riyal', cc: 'QAR', symbol: '﷼' },
  { country: 'Russia', name: 'Russian Ruble', cc: 'RUB', symbol: '₽' },
  { country: 'Saudi Arabia', name: 'Saudi Arabian Riyal', cc: 'SAR', symbol: '﷼' },
  { country: 'Singapore', name: 'Singapore Dollar', cc: 'SGD', symbol: '$' },
  { country: 'South Korea', name: 'Korean Won', cc: 'KRW', symbol: '₩' },
  { country: 'Sri Lanka', name: 'Sri Lankan Rupee', cc: 'LKR', symbol: '₨' },
  { country: 'Syria', name: 'Syrian Pound', cc: 'SYP', symbol: '£' },
  { country: 'Taiwan', name: 'New Taiwan Dollar', cc: 'TWD', symbol: 'NT$' },
  { country: 'Tajikistan', name: 'Tajikistan Somoni', cc: 'TJS', symbol: 'ЅM' },
  { country: 'Thailand', name: 'Thai Baht', cc: 'THB', symbol: '฿' },
  { country: 'Timor-Leste', name: 'United States Dollar', cc: 'USD', symbol: '$' },
  { country: 'Turkey', name: 'Turkish New Lira', cc: 'TRY', symbol: '₺' },
  { country: 'Turkmenistan', name: 'Turkmenistani Manat', cc: 'TMM', symbol: 'T' },
  { country: 'United Arab Emirates (UAE)', name: 'United Arab Emirates Dirham', cc: 'AED', symbol: 'د.إ' },
  { country: 'Uzbekistan', name: 'Uzbekistani Som', cc: 'UZS', symbol: 'лв' },
  { country: 'Vietnam', name: 'Viet Nam Dong', cc: 'VND', symbol: '₫' },
  { country: 'Yemen', name: 'Yemeni Rial', cc: 'YER', symbol: '﷼' },
  { country: 'Country', name: 'Currency', cc: 'Code', symbol: 'Symbol' },
  { country: 'Algeria', name: 'Algerian Dinar', cc: 'DZD', symbol: 'دج' },
  { country: 'Angola', name: 'Angolan Kwanza', cc: 'AOA', symbol: 'Kz' },
  { country: 'Benin', name: 'West African CFA', cc: 'XOF', symbol: 'CFA' },
  { country: 'Botswana', name: 'Botswana Pula', cc: 'BWP', symbol: 'P' },
  { country: 'Burkina Faso', name: 'West African CFA', cc: 'XOF', symbol: 'CFA' },
  { country: 'Burundi', name: 'Burundian Franc', cc: 'BIF', symbol: 'FBu' },
  { country: 'Cabo Verde', name: 'Cape Verde Escudo', cc: 'CVE', symbol: '$' },
  { country: 'Cameroon', name: 'Central African CFA', cc: 'XAF', symbol: 'FCFA' },
  { country: 'Central African Republic (CAR)', name: 'Central African CFA', cc: 'XAF', symbol: 'FCFA' },
  { country: 'Chad', name: 'Central African CFA', cc: 'XAF', symbol: 'FCFA' },
  { country: 'Comoros', name: 'Comorian Franc', cc: 'KMF', symbol: 'CF' },
  { country: 'Democratic Republic of the Congo', name: 'Congolese franc', cc: 'CDF', symbol: 'FC' },
  { country: 'Republic of the Congo', name: 'Central African CFA', cc: 'XAF', symbol: 'FCFA' },
  { country: "Cote d'Ivoire", name: 'West African CFA', cc: 'XOF', symbol: 'CFA' },
  { country: 'Djibouti', name: 'Djiboutian Franc', cc: 'DJF', symbol: 'Fdj' },
  { country: 'Egypt', name: 'Egyptian Pound', cc: 'EGP', symbol: '£' },
  { country: 'Equatorial Guinea', name: 'Central African CFA', cc: 'XAF', symbol: 'FCFA' },
  { country: 'Eritrea', name: 'Eritrean Nakfa', cc: 'ERN', symbol: 'ናቕፋ' },
  { country: 'Ethiopia', name: 'Ethiopian Birr', cc: 'ETB', symbol: 'ብር' },
  { country: 'Gabon', name: 'Central African CFA', cc: 'XAF', symbol: 'FCFA' },
  { country: 'Gambia', name: 'Gambian Dalasi', cc: 'GMD', symbol: 'D' },
  { country: 'Ghana', name: 'Ghanaian Cedi', cc: 'GHC', symbol: 'GH₵' },
  { country: 'Guinea', name: 'Guinean Franc', cc: 'GNF', symbol: 'FG' },
  { country: 'Guinea-Bissau', name: 'West African CFA', cc: 'XOF', symbol: 'CFA' },
  { country: 'Kenya', name: 'Kenyan Shilling', cc: 'KES', symbol: 'KSh,' },
  { country: 'Lesotho', name: 'Lesotho Loti', cc: 'LSL', symbol: 'L ' },
  { country: 'Liberia', name: 'Liberian Dollar', cc: 'LRD', symbol: '$' },
  { country: 'Libya', name: 'Libyan Dinar', cc: 'LYD', symbol: 'ل.د' },
  { country: 'Madagascar', name: 'Malagasy Ariary', cc: 'MGA', symbol: 'Ar' },
  { country: 'Malawi', name: 'Malawian Kwacha', cc: 'MWK', symbol: 'MK' },
  { country: 'Mali', name: 'West African CFA', cc: 'XOF', symbol: 'CFA' },
  { country: 'Mauritania', name: 'Mauritanian Ouguiya', cc: 'MRO', symbol: 'UM' },
  { country: 'Mauritius', name: 'Mauritian Rupee', cc: 'MUR', symbol: '₨' },
  { country: 'Morocco', name: 'Moroccan Dirham', cc: 'MAD', symbol: 'DH' },
  { country: 'Mozambique', name: 'Mozambican Metical', cc: 'MZN', symbol: 'MT' },
  { country: 'Namibia', name: 'Namibian Dollar', cc: 'NAD', symbol: '$' },
  { country: 'Niger', name: 'West African CFA', cc: 'XOF', symbol: 'CFA' },
  { country: 'Nigeria', name: 'Nigerian Naira', cc: 'NGN', symbol: '₦' },
  { country: 'Rwanda', name: 'Rwandan Franc', cc: 'RWF', symbol: 'FRw' },
  { country: 'Sao Tome and Principe', name: 'Sao Tome Dobra', cc: 'STD', symbol: ' Db' },
  { country: 'Senegal', name: 'West African CFA', cc: 'XOF', symbol: 'CFA' },
  { country: 'Seychelles', name: 'Seychelles Rupee', cc: 'SCR', symbol: '₨' },
  { country: 'Sierra Leone', name: 'Sierra Leonean Leone', cc: 'SLL', symbol: 'Le' },
  { country: 'Somalia', name: 'Somali Shilling', cc: 'SOS', symbol: 'S' },
  { country: 'South Africa', name: 'South African Rand', cc: 'ZAR', symbol: 'R' },
  { country: 'South Sudan', name: 'South Sudanese pound', cc: 'SSP', symbol: '£' },
  { country: 'Sudan', name: 'Sudanese pound', cc: 'SDG', symbol: 'SD' },
  { country: 'Swaziland', name: 'Swazi Lilangeni', cc: 'SZL', symbol: 'E ' },
  { country: 'Tanzania', name: 'Tanzanian Shilling', cc: 'TZS', symbol: 'TSh' },
  { country: 'Togo', name: 'West African CFA', cc: 'XOF', symbol: 'CFA' },
  { country: 'Tunisia', name: 'Tunisian Dinar', cc: 'TND', symbol: 'د.ت' },
  { country: 'Uganda', name: 'Ugandan Shilling', cc: 'UGX', symbol: 'USh' },
  { country: 'Zambia', name: 'Zambian Kwacha', cc: 'ZMK', symbol: 'ZK' },
  { country: 'Zimbabwe', name: 'Zimbabwean Dollar', cc: 'ZWD', symbol: '$' },
  { country: 'Country', name: 'Currency', cc: 'Code', symbol: 'Symbol' },
  { country: 'Albania', name: 'Albanian Lek', cc: 'ALL', symbol: 'Lek' },
  { country: 'Andorra', name: 'European Euro', cc: 'EUR', symbol: '€' },
  { country: 'Armenia', name: 'Armenian Dram', cc: 'AMD', symbol: 'դր.' },
  { country: 'Austria', name: 'European Euro', cc: 'EUR', symbol: '€' },
  { country: 'Azerbaijan', name: 'Azerbaijani Manat', cc: 'AZN', symbol: '₼' },
  { country: 'Belarus', name: 'Belarusian Ruble', cc: 'BYR', symbol: 'Br' },
  { country: 'Belgium', name: 'European Euro', cc: 'EUR', symbol: '€' },
  { country: 'Bosnia and Herzegovina', name: 'Bosnia-Herzegovina Convertible Mark', cc: 'BAM', symbol: 'KM' },
  { country: 'Bulgaria', name: 'Bulgarian Lev', cc: 'BGN', symbol: 'лв' },
  { country: 'Croatia', name: 'Croatian Kuna', cc: 'HRK', symbol: 'kn' },
  { country: 'Cyprus', name: 'Cypriot Pound', cc: 'CYP', symbol: '£' },
  { country: 'Czech Republic', name: 'Czech Koruna', cc: 'CZK', symbol: 'Kč' },
  { country: 'Denmark', name: 'Danish Krone', cc: 'DKK', symbol: 'kr.' },
  { country: 'Estonia', name: 'Estonian Kroon', cc: 'EEK', symbol: 'EEK' },
  { country: 'Finland', name: 'European Euro', cc: 'EUR', symbol: '€' },
  { country: 'France', name: 'European Euro', cc: 'EUR', symbol: '€' },
  { country: 'Georgia', name: 'Georgian Lari', cc: 'GEL', symbol: 'ლ' },
  { country: 'Germany', name: 'European Euro', cc: 'EUR', symbol: '€' },
  { country: 'Greece', name: 'European Euro', cc: 'EUR', symbol: '€' },
  { country: 'Hungary', name: 'Hungarian Forint', cc: 'HUF', symbol: 'Ft' },
  { country: 'Iceland', name: 'Icelandic Krona', cc: 'ISK', symbol: 'kr' },
  { country: 'Ireland', name: 'European Euro', cc: 'EUR', symbol: '€' },
  { country: 'Italy', name: 'European Euro', cc: 'EUR', symbol: '€' },
  { country: 'Kazakhstan', name: 'Kazakhstani Tenge', cc: 'KZT', symbol: 'лв' },
  { country: 'Kosovo', name: 'Euro', cc: 'EUR', symbol: '€' },
  { country: 'Latvia', name: 'Latvian Lats', cc: 'LVL', symbol: 'Ls' },
  { country: 'Liechtenstein', name: 'Swiss Franc', cc: 'CHF', symbol: 'CHF' },
  { country: 'Lithuania', name: 'Lithuanian Litas', cc: 'LTL', symbol: 'Lt ' },
  { country: 'Luxembourg', name: 'European Euro', cc: 'EUR', symbol: '€' },
  { country: 'Macedonia (FYROM)', name: 'Macedonian Denar', cc: 'MKD', symbol: 'ден' },
  { country: 'Malta', name: 'Maltese Lira', cc: 'MTL', symbol: '₤' },
  { country: 'Moldova', name: 'Moldovan Leu', cc: 'MDL', symbol: 'L' },
  { country: 'Monaco', name: 'European Euro', cc: 'EUR', symbol: '€' },
  { country: 'Montenegro', name: 'European Euro', cc: 'EUR', symbol: '€' },
  { country: 'Netherlands', name: 'European Euro', cc: 'EUR', symbol: '€' },
  { country: 'Norway', name: 'Norwegian Krone', cc: 'NOK', symbol: 'kr' },
  { country: 'Poland', name: 'Polish Zloty', cc: 'PLN', symbol: 'zł' },
  { country: 'Portugal', name: 'European Euro', cc: 'EUR', symbol: '€' },
  { country: 'Romania', name: 'Romanian Leu', cc: 'RON', symbol: 'lei' },
  { country: 'Russia', name: 'Russian Ruble', cc: 'RUB', symbol: '₽' },
  { country: 'San Marino', name: 'European Euro', cc: 'EUR', symbol: '€' },
  { country: 'Serbia', name: 'Serbian Dinar', cc: 'RSD', symbol: 'Дин.' },
  { country: 'Slovakia', name: 'Slovak Koruna', cc: 'SKK', symbol: 'Sk' },
  { country: 'Slovenia', name: 'European Euro', cc: 'EUR', symbol: '€' },
  { country: 'Spain', name: 'European Euro', cc: 'EUR', symbol: '€' },
  { country: 'Sweden', name: 'Swedish Krona', cc: 'SEK', symbol: 'kr' },
  { country: 'Switzerland', name: 'Swiss Franc', cc: 'CHF', symbol: 'CHF' },
  { country: 'Turkey', name: 'Turkish New Lira', cc: 'TRY', symbol: '₺' },
  { country: 'Ukraine', name: 'Ukrainian Hryvnia', cc: 'UAH', symbol: '₴' },
  { country: 'United Kingdom (UK)', name: 'United Kingdom Pound Sterling', cc: 'GBP', symbol: '£' },
  { country: 'Vatican City (Holy See)', name: 'European Euro', cc: 'EUR', symbol: '€' },
  { country: 'Country', name: 'Currency', cc: 'Code', symbol: 'Symbol' },
  { country: 'Antigua and Barbuda', name: 'East Caribbean Dollar', cc: 'XCD', symbol: '$' },
  { country: 'Bahamas', name: 'Bahamian Dollar', cc: 'BSD', symbol: '$' },
  { country: 'Barbados', name: 'Barbados Dollar', cc: 'BBD', symbol: '$' },
  { country: 'Belize', name: 'Belize Dollar', cc: 'BZD', symbol: 'BZ$' },
  { country: 'Canada', name: 'Canadian Dollar', cc: 'CAD', symbol: '$' },
  { country: 'Costa Rica', name: 'Costa Rican Colon', cc: 'CRC', symbol: '₡' },
  { country: 'Cuba', name: 'Cuban Convertible Peso', cc: 'CUC', symbol: '$' },
  { country: 'Dominica', name: 'East Caribbean Dollar', cc: 'XCD', symbol: '$' },
  { country: 'Dominican Republic', name: 'Dominican Peso', cc: 'DOP', symbol: 'RD$' },
  { country: 'El Salvador', name: 'United States Dollar', cc: 'USD', symbol: '$' },
  { country: 'Grenada', name: 'East Caribbean Dollar', cc: 'XCD', symbol: '$' },
  { country: 'Guatemala', name: 'Guatemalan Quetzal', cc: 'GTQ', symbol: 'Q' },
  { country: 'Haiti', name: 'Haitian Gourde', cc: 'HTG', symbol: 'G' },
  { country: 'Honduras', name: 'Honduran Lempira', cc: 'HNL', symbol: 'L' },
  { country: 'Jamaica', name: 'Jamaican Dollar', cc: 'JMD', symbol: 'J$' },
  { country: 'Mexico', name: 'Mexican Peso', cc: 'MXN', symbol: '$' },
  { country: 'Nicaragua', name: 'Nicaraguan Córdoba', cc: 'NIO', symbol: 'C$' },
  { country: 'Panama', name: 'Panamanian Balboa', cc: 'PAB', symbol: 'B/.' },
  { country: 'Saint Kitts and Nevis', name: 'East Caribbean Dollar', cc: 'XCD', symbol: '$' },
  { country: 'Saint Lucia', name: 'East Caribbean Dollar', cc: 'XCD', symbol: '$' },
  { country: 'Saint Vincent and the Grenadines', name: 'East Caribbean Dollar', cc: 'XCD', symbol: '$' },
  { country: 'Trinidad and Tobago', name: 'Trinidad and Tobago Dollar', cc: 'TTD', symbol: 'TT$' },
  { country: 'United States of America (USA)', name: 'United States Dollar', cc: 'USD', symbol: '$' },
  { country: 'Country', name: 'Currency', cc: 'Code', symbol: 'Symbol' },
  { country: 'Argentina', name: 'Argentine Peso', cc: 'ARS', symbol: '$' },
  { country: 'Bolivia', name: 'Bolivian Boliviano', cc: 'BOB', symbol: '$b' },
  { country: 'Brazil', name: 'Brazilian Real', cc: 'BRL', symbol: 'R$' },
  { country: 'Chile', name: 'Chilean Peso', cc: 'CLP', symbol: '$' },
  { country: 'Colombia', name: 'Colombian Peso', cc: 'COP', symbol: '$' },
  { country: 'Ecuador', name: 'United States Dollar', cc: 'USD', symbol: '$' },
  { country: 'Guyana', name: 'Guyanese Dollar', cc: 'GYD', symbol: '$' },
  { country: 'Paraguay', name: 'Paraguay Guarani', cc: 'PYG', symbol: 'Gs' },
  { country: 'Peru', name: 'Peruvian Nuevo Sol', cc: 'PEN', symbol: 'S/.' },
  { country: 'Suriname', name: 'Suriname Dollar', cc: 'SRD', symbol: '$' },
  { country: 'Uruguay', name: 'Uruguayan peso', cc: 'UYU', symbol: '$U' },
  { country: 'Venezuela', name: 'Venezuelan Bolivar', cc: 'VEF', symbol: 'Bs' },
  { country: 'Country', name: 'Currency', cc: 'Code', symbol: 'Symbol' },
  { country: 'Australia', name: 'Australian Dollar', cc: 'AUD', symbol: '$' },
  { country: 'Fiji', name: 'Fiji Dollar', cc: 'FJD', symbol: '$' },
  { country: 'Kiribati', name: 'Australian Dollar', cc: 'AUD', symbol: '$' },
  { country: 'Marshall Islands', name: 'United States Dollar', cc: 'USD', symbol: '$' },
  { country: 'Micronesia', name: 'United States Dollar', cc: 'USD', symbol: '$' },
  { country: 'Nauru', name: 'Australian Dollar', cc: 'AUD', symbol: '$' },
  { country: 'New Zealand', name: 'New Zealand Dollar', cc: 'NZD', symbol: '$' },
  { country: 'Palau', name: 'United States Dollar', cc: 'USD', symbol: '$' },
  { country: 'Papua New Guinea', name: 'Papua New Guinea Kina', cc: 'PGK', symbol: 'K' },
  { country: 'Samoa', name: 'Samoan Tala', cc: 'WST', symbol: 'WS$' },
  { country: 'Solomon Islands', name: 'Solomon Islands Dollar', cc: 'SBD', symbol: '$' },
  { country: 'Tonga', name: "Tongan Pa'Anga", cc: 'TOP', symbol: 'T$' },
  { country: 'Tuvalu', name: 'Australian Dollar', cc: 'AUD', symbol: '$' },
  { country: 'Vanuatu', name: 'Vanuatu Vatu', cc: 'VUV', symbol: 'VT' },
];
